displayName=Gielinor Español
author=Sants
description=Community-driven Spanish localization for Old School RuneScape.
tags=spanish,espanol,translation,localization,osrs
version=0.0.1
plugins=com.sspencerd.gielinorespanol.GielinorEspanolPlugin
build=standard